version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/" # Location of your .csproj or .sln file(s)
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"